A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


In [1]:
from scipy import stats 
import pandas as pd 
import numpy as np
import scipy 

In [4]:
cutlets = pd.read_csv("cutlets.csv")
cutlets.head(10)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522
5  7.3871  6.8110
6  6.8755  7.2212
7  7.0621  6.6606
8  6.6840  7.2402
9  6.8236  7.0503

In [7]:
unitA=pd.Series(cutlets.iloc[:,0])

In [9]:
unitB=pd.Series(cutlets.iloc[:,1])

In [17]:
#2 sample test 2-tail t-test
t_statistic, p_value = stats.ttest_ind(unitA, unitB)
t_statistic, p_value

(0.7228688704678063, 0.4722394724599501)

In [18]:
alpha = 0.025
print('Significance=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject the null hypothesis; there is a significant difference between two Units A and B.')
else:
    print('We fail to reject the null hypothesis.')



Significance=0.025, p=0.472
We fail to reject the null hypothesis.


In [ ]:
#We fail to reject Null Hypothesis because of lack of evidence, 
#there is no significant difference between the two samples

A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.


In [19]:
TAT = pd.read_csv("LabTAT.csv")
TAT.head(10)

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60
5        179.45        197.00        181.51        161.12
6        191.37        166.36        214.21        154.02
7        166.81        169.60        183.43        163.25
8        158.81        175.36        191.60        152.79
9        165.88        198.68        208.43        161.98

In [20]:
#Null Hypothesis:  μ1 =  μ1 =  μ3 =  μ4
#Alternative Hypthosis: Atleast One of them is Different

In [23]:
L1=pd.Series(TAT.iloc[:,0])

In [25]:
L2=pd.Series(TAT.iloc[:,1])

In [26]:
L3=pd.Series(TAT.iloc[:,2])

In [30]:
L4=pd.Series(TAT.iloc[:,3])

In [28]:
test_statistic , p_value = stats.f_oneway(L1,L2,L3,L4)
print('p_value =',p_value)

p_value = 6.30968580921409e-55


In [35]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('Reject Null Hypothesis as there is a significance difference between TAT of reports of  the laboratories')
else:
    print('Fail to reject Null hypothesis')

Significnace=0.050, p=0.000
Reject Null Hypothesis as there is a significance difference between TAT of reports of  the laboratories


In [36]:
#Fail to reject Null Hypothesis because of lack evidence,
#there is no significant difference between the samples

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.
H0 = All proportions are equal
Ha = Not all proportions are equal 
1. Check P value 
2. If p-Value < alpha, we reject Null Hypothesis


In [67]:
Buyer = pd.read_csv("BuyerRatio.csv")
Buyer.head(10)

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [68]:
#Null Hypothesis: There is no association between the gender based buyer ratio across regions
#Alternative Hypthosis: There is a significant association between the gender based buyer ration across regions

In [69]:
#one tailed: 1 - 0.95 = 0.05 

In [70]:
from scipy.stats import chi2_contingency

In [71]:
#chi square test - convert observed value into expected value 
stat, p, dof, exp = chi2_contingency(Buyer.iloc[:, 1:])
print("Chi-square statistic:", stat)
print("p-value:", p)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", exp)

Chi-square statistic: 1.595945538661058
p-value: 0.6603094907091882
Degrees of freedom: 3
Expected frequencies:
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [72]:
stats.chi2_contingency(table) 

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [73]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [74]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [75]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.810
We fail to reject Null hypothesis


In [65]:
#We fail to reject Null Hypothesis because of lack evidence. 
#Therefore, there is no association between male-female buyers rations
#and are similar across regions Hence, Independent samples

TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [79]:
Order = pd.read_csv("Costomer+OrderForm.csv")
Order.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [82]:
print(Order['Phillippines'].value_counts(),Order['Indonesia'].value_counts(),Order['Malta'].value_counts(),Order['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


In [83]:
observed=([[271,267,269,280],[29,33,31,20]])

In [85]:
stat, p, df, exp = stats.chi2_contingency(observed)
print("Statistics = ",stat,"\n",'P_Value = ', p,'\n', 'degree of freedom =', df,'\n', 'Expected Values = ', exp)

Statistics =  3.858960685820355 
 P_Value =  0.2771020991233135 
 degree of freedom = 3 
 Expected Values =  [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [86]:
observed = np.array([271, 267, 269, 280, 29, 33, 31, 20])
expected = np.array([271.75, 271.75, 271.75, 271.75, 28.25, 28.25, 28.25, 28.25])

In [87]:
test_statistic , p_value = stats.chisquare(observed, expected, ddof = df)
print("Test Statistic = ",test_statistic,'\n', 'p_value =',p_value)

Test Statistic =  3.858960685820355 
 p_value = 0.4254298144535761


In [89]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis due to lack of evidence')

Significnace=0.050, p=0.425
We fail to reject Null hypothesis due to lack of evidence
